use_frameworks!

target 'CZQLessonMainKit_Example' do
  pod 'CZQLessonMainKit', :path => '../'

  target 'CZQLessonMainKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
